package io.fluxora.platform.model;

import io.fluxora.platform.upstream.dto.UpstreamPage;
import io.fluxora.platform.identity.entity.UserAccount;
import io.fluxora.platform.upstream.provider.ProviderException;
import io.fluxora.common.error.BusinessErrorCode;
import org.springframework.security.core.Authentication;
import io.fluxora.platform.upstream.channel.ProviderChannelMapper;
import java.math.BigDecimal;
import io.fluxora.platform.billing.CnyPrecisionPolicy;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/** 平台统一模型目录查询服务；写操作将在同一领域服务中按租户边界实现。 */
@Service
public class ModelCatalogService {
    private final ModelCatalogMapper mapper;
    private final ProviderChannelMapper channelMapper;
    private final ProviderModelDiscoveryService discoveryService;
    public ModelCatalogService(ModelCatalogMapper mapper, ProviderChannelMapper channelMapper, ProviderModelDiscoveryService discoveryService) { this.mapper = mapper; this.channelMapper=channelMapper; this.discoveryService=discoveryService; }
    @Transactional(readOnly = true)
    public UpstreamPage<PlatformModelSummary> listPlatformModels(String keyword, Boolean enabled, int page, int size) {
        int safePage=Math.max(1,page), safeSize=Math.max(1,Math.min(size,100));
        String query=keyword==null||keyword.isBlank()?null:keyword.trim();
        return new UpstreamPage<>(mapper.findPlatformModels(query,enabled,(safePage-1)*safeSize,safeSize),mapper.countPlatformModels(query,enabled),safePage,safeSize);
    }
    @Transactional
    public PlatformModelSummary createPlatformModel(PlatformModel model, UserAccount user, Authentication auth) {
        assertPlatformAdmin(auth); validate(model);
        if (mapper.existsPlatformCode(model.getCode().trim())) throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"该平台模型编码已被使用，请选择已有模型或更换编码");
        model.setCode(model.getCode().trim()); model.setDisplayName(model.getDisplayName().trim()); model.setCreatedBy(user.getId()); model.setUpdatedBy(user.getId()); mapper.insertPlatformModel(model);
        return mapper.findPlatformModel(model.getId()).orElseThrow(() -> new ProviderException(BusinessErrorCode.INTERNAL_ERROR,"模型创建失败"));
    }
    @Transactional
    public PlatformModelSummary updatePlatformModel(Long id, PlatformModel input, UserAccount user, Authentication auth) {
        assertPlatformAdmin(auth); PlatformModelSummary current=mapper.findPlatformModel(id).orElseThrow(() -> new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"平台模型不存在"));
        input.setId(id); input.setCode(current.getCode()); input.setCreatedBy(user.getId()); input.setUpdatedBy(user.getId()); validate(input); mapper.updatePlatformModel(input);
        return mapper.findPlatformModel(id).orElseThrow(() -> new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"平台模型不存在"));
    }
    @Transactional public void setPlatformModelEnabled(Long id, boolean enabled, Authentication auth) { assertPlatformAdmin(auth); if(mapper.findPlatformModel(id).isEmpty()) throw new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"平台模型不存在"); mapper.setPlatformModelEnabled(id,enabled); }
    private void assertPlatformAdmin(Authentication auth) { if(auth==null||auth.getAuthorities().stream().noneMatch(a->"ROLE_PLATFORM_ADMIN".equals(a.getAuthority()))) throw new ProviderException(BusinessErrorCode.ACCESS_DENIED,"当前账号没有此操作权限"); }
    private void validate(PlatformModel model) { if(model.getCode()==null||!model.getCode().matches("[A-Za-z0-9._-]{1,128}")||model.getDisplayName()==null||model.getDisplayName().isBlank()||model.getDisplayName().length()>256||(model.getContextLength()!=null&&model.getContextLength()<1)||(model.getMaxOutputLength()!=null&&model.getMaxOutputLength()<1)) throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"请填写有效的平台模型信息"); }
    @Transactional(readOnly=true) public UpstreamPage<ProviderChannelModelSummary> listChannelModels(Long channelId,UserAccount user,Authentication auth,String keyword,Boolean enabled,int page,int size){assertChannelVisible(channelId,user,auth);int safePage=Math.max(1,page),safeSize=Math.max(1,Math.min(size,100));String q=keyword==null||keyword.isBlank()?null:keyword.trim();Long tenant=channelMapper.findById(channelId).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"上游通道不存在")).getTenantId();return new UpstreamPage<>(mapper.findChannelModels(channelId,tenant,q,enabled,(safePage-1)*safeSize,safeSize),mapper.countChannelModels(channelId,tenant,q,enabled),safePage,safeSize);}
    @Transactional public ProviderChannelModelSummary createManualChannelModel(Long channelId,String upstreamModelId,String displayName,UserAccount user,Authentication auth){assertChannelVisible(channelId,user,auth);if(upstreamModelId==null||upstreamModelId.isBlank()||upstreamModelId.length()>256||displayName==null||displayName.isBlank()||displayName.length()>256)throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"请填写有效的上游模型信息");if(mapper.existsChannelModel(channelId,upstreamModelId.trim()))throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"当前通道已存在该上游模型，无需重复添加");Long tenant=channelMapper.findById(channelId).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"上游通道不存在")).getTenantId();mapper.insertChannelModel(tenant,channelId,upstreamModelId.trim(),displayName.trim(),user.getId());return mapper.findChannelModels(channelId,tenant,upstreamModelId.trim(),null,0,1).stream().findFirst().orElseThrow(()->new ProviderException(BusinessErrorCode.INTERNAL_ERROR,"上游模型创建失败"));}
    /** 候选编辑和软删均先按所属通道校验，避免仅凭候选 ID 越过租户边界。 */
    @Transactional public ProviderChannelModelSummary updateChannelModel(Long id,String displayName,boolean enabled,UserAccount user,Authentication auth){ProviderChannelModelSummary current=mapper.findChannelModel(id).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"上游模型不存在"));assertChannelVisible(current.getProviderChannelId(),user,auth);if(displayName==null||displayName.isBlank()||displayName.length()>256)throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"请填写有效的上游模型名称");mapper.updateChannelModel(id,displayName.trim(),enabled,user.getId());return mapper.findChannelModel(id).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"上游模型不存在"));}
    @Transactional public void deleteChannelModel(Long id,UserAccount user,Authentication auth){ProviderChannelModelSummary current=mapper.findChannelModel(id).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"上游模型不存在"));assertChannelVisible(current.getProviderChannelId(),user,auth);mapper.softDeleteChannelModel(id,user.getId());}
    @Transactional public ProviderChannelModelSummary mapChannelModel(Long id,Long platformModelId,UserAccount user,Authentication auth){assertPlatformAdmin(auth);ProviderChannelModelSummary current=mapper.findChannelModel(id).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"上游模型不存在"));if(platformModelId!=null&&mapper.findPlatformModel(platformModelId).isEmpty())throw new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"平台模型不存在");mapper.mapChannelModel(id,platformModelId,user.getId());return mapper.findChannelModel(id).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"上游模型不存在"));}
    private void assertChannelVisible(Long channelId,UserAccount user,Authentication auth){var channel=channelMapper.findById(channelId).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"上游通道不存在或不可访问"));if(!isPlatform(auth)&&!channel.getTenantId().equals(user.getTenantId()))throw new ProviderException(BusinessErrorCode.ACCESS_DENIED,"当前账号没有此操作权限");}
    private boolean isPlatform(Authentication auth){return auth!=null&&auth.getAuthorities().stream().anyMatch(a->"ROLE_PLATFORM_ADMIN".equals(a.getAuthority()));}
    @Transactional public SyncResult syncChannelModels(Long channelId,Long credentialId,UserAccount user,Authentication auth){assertChannelVisible(channelId,user,auth);ChannelDiscoveryInfo info=mapper.findChannelDiscoveryInfo(channelId).orElseThrow(()->new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"当前通道不可用于模型同步"));if(!"OPENAI".equals(info.protocol()))throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"当前上游不支持自动同步模型，请手工新增模型");var discovery=discoveryService.discoverOpenAiModels(channelId,info.normalizedBaseUrl(),credentialId);var names=discovery.modelIds().stream().distinct().toList();var items=new java.util.ArrayList<SyncItemResult>(discovery.failures());if(names.isEmpty())return new SyncResult(0,0,discovery.modelIds().size(),discovery.failures().size(),items);var existing=mapper.findExistingChannelModelIds(channelId,names);var existingSet=new java.util.HashSet<>(existing);mapper.batchUpsertSyncedChannelModels(info.tenantId(),channelId,names,credentialId,user.getId());for(String name:names)items.add(new SyncItemResult(name,existingSet.contains(name)?"UPDATED":"ADDED",existingSet.contains(name)?"已更新同步时间":"已新增候选"));var seen=new java.util.HashSet<String>();for(String name:discovery.modelIds())if(!seen.add(name))items.add(new SyncItemResult(name,"SKIPPED","上游响应内重复"));return new SyncResult(names.size()-existing.size(),existing.size(),discovery.modelIds().size()-names.size(),discovery.failures().size(),items);}
    @Transactional(readOnly=true) public UpstreamPage<TenantModelSummary> listTenantModels(Long requestedTenantId,UserAccount user,Authentication auth,int page,int size){Long tenant=resolveTenant(requestedTenantId,user,auth);int p=Math.max(1,page),s=Math.max(1,Math.min(100,size));return new UpstreamPage<>(mapper.findTenantModels(tenant,(p-1)*s,s),mapper.countTenantModels(tenant),p,s);}
    @Transactional public TenantModelSummary publishTenantModel(Long requestedTenantId,Long platformModelId,String displayName,String description,UserAccount user,Authentication auth){Long tenant=resolveTenant(requestedTenantId,user,auth);PlatformModelSummary platform=mapper.findPlatformModel(platformModelId).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"平台模型不存在"));if(!"ENABLED".equals(platform.getStatus()))throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"平台模型当前不可发布");if(mapper.existsTenantModel(tenant,platformModelId))throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"当前租户已发布该平台模型");mapper.insertTenantModel(tenant,platformModelId,blank(displayName),blank(description),user.getId());return mapper.findTenantModels(tenant,0,1).stream().findFirst().orElseThrow(()->new ProviderException(BusinessErrorCode.INTERNAL_ERROR,"租户模型发布失败"));}
    private Long resolveTenant(Long requested,UserAccount user,Authentication auth){if(isPlatform(auth)){if(requested==null)throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"请选择目标租户");return requested;}if(user.getTenantId()==null||(requested!=null&&!requested.equals(user.getTenantId())))throw new ProviderException(BusinessErrorCode.ACCESS_DENIED,"当前账号没有此操作权限");return user.getTenantId();}
    private String blank(String value){return value==null||value.isBlank()?null:value.trim();}
    @Transactional(readOnly=true) public PriceView currentPlatformPrice(Long platformModelId){return mapper.currentPlatformPrice(platformModelId).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"平台模型尚未配置默认价格"));}
    @Transactional(readOnly=true) public java.util.List<PriceView> platformPriceHistory(Long platformModelId,Authentication auth){assertPlatformAdmin(auth);return mapper.platformPriceHistory(platformModelId);}
    @Transactional public PriceView createPlatformPrice(Long platformModelId,String input,String output,String cacheWrite,String cacheRead,UserAccount user,Authentication auth){assertPlatformAdmin(auth);PlatformModelSummary model=mapper.findPlatformModel(platformModelId).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"平台模型不存在"));BigDecimal[] p=prices(input,output,cacheWrite,cacheRead,model.isSupportsCache());mapper.expirePlatformPrice(platformModelId);mapper.insertPlatformPrice(platformModelId,p[0],p[1],p[2],p[3],user.getId());return currentPlatformPrice(platformModelId);}
    @Transactional(readOnly=true) public PriceView currentTenantPrice(Long tenantModelId,UserAccount user,Authentication auth){TenantModelSummary tm=requireTenantModel(tenantModelId,user,auth);if("INHERIT_PLATFORM_DEFAULT".equals(tm.getPriceMode()))return currentPlatformPrice(tm.getPlatformModelId());return mapper.currentTenantPrice(tenantModelId).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"模型尚未配置有效价格"));}
    @Transactional(readOnly=true) public java.util.List<PriceView> tenantPriceHistory(Long tenantModelId,UserAccount user,Authentication auth){requireTenantModel(tenantModelId,user,auth);return mapper.tenantPriceHistory(tenantModelId);}
    @Transactional public PriceView setTenantCustomPrice(Long tenantModelId,String input,String output,String cacheWrite,String cacheRead,UserAccount user,Authentication auth){TenantModelSummary tm=requireTenantModel(tenantModelId,user,auth);BigDecimal[] p=prices(input,output,cacheWrite,cacheRead,tm.isSupportsCache());mapper.expireTenantPrice(tenantModelId);mapper.insertTenantPrice(tenantModelId,p[0],p[1],p[2],p[3],user.getId());mapper.setTenantPriceMode(tenantModelId,"TENANT_CUSTOM",user.getId());return currentTenantPrice(tenantModelId,user,auth);}
    @Transactional public void inheritPlatformPrice(Long tenantModelId,UserAccount user,Authentication auth){TenantModelSummary tm=requireTenantModel(tenantModelId,user,auth);currentPlatformPrice(tm.getPlatformModelId());mapper.setTenantPriceMode(tenantModelId,"INHERIT_PLATFORM_DEFAULT",user.getId());}
    @Transactional public void enableTenantModel(Long tenantModelId,UserAccount user,Authentication auth){requireTenantModel(tenantModelId,user,auth);if(!mapper.tenantModelCanEnable(tenantModelId))throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"请至少配置一个可用上游路由和有效价格后再发布模型");mapper.setTenantModelStatus(tenantModelId,"ENABLED",user.getId());}
    private TenantModelSummary requireTenantModel(Long id,UserAccount user,Authentication auth){TenantModelSummary tm=mapper.findTenantModel(id).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"租户模型不存在"));if(!isPlatform(auth)&&!tm.getTenantId().equals(user.getTenantId()))throw new ProviderException(BusinessErrorCode.ACCESS_DENIED,"当前账号没有此操作权限");return tm;}
    /** 统一四项价格的精度和缓存完整性校验；展示字符串唯一经 CnyPrecisionPolicy 转换为精确值。 */
    private BigDecimal[] prices(String input,String output,String cacheWrite,String cacheRead,boolean cache){try{BigDecimal in=decimal(input),out=decimal(output);if(!cache){return new BigDecimal[]{in,out,null,null};}if(cacheWrite==null||cacheWrite.isBlank()||cacheRead==null||cacheRead.isBlank())throw new IllegalArgumentException();return new BigDecimal[]{in,out,decimal(cacheWrite),decimal(cacheRead)};}catch(Exception e){throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"请输入有效的人民币价格");}}
    private BigDecimal decimal(String value){return new BigDecimal(CnyPrecisionPolicy.formatAtoms(CnyPrecisionPolicy.toAtoms(value)));}
    @Transactional(readOnly=true) public java.util.List<ModelRouteSummary> routes(Long tenantModelId,UserAccount user,Authentication auth){requireTenantModel(tenantModelId,user,auth);return mapper.findRoutes(tenantModelId);}
    @Transactional public ModelRouteSummary createRoute(Long tenantModelId,String protocol,String remark,UserAccount user,Authentication auth){requireTenantModel(tenantModelId,user,auth);if(!"OPENAI".equals(protocol)&&!"ANTHROPIC".equals(protocol))throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"请选择有效的入站协议");if(mapper.existsRouteProtocol(tenantModelId,protocol))throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"当前模型已配置该入站协议路由");mapper.insertRoute(tenantModelId,protocol,blank(remark),user.getId());return mapper.findRoutes(tenantModelId).stream().filter(x->protocol.equals(x.getInboundProtocol())).findFirst().orElseThrow(()->new ProviderException(BusinessErrorCode.INTERNAL_ERROR,"路由创建失败"));}
    @Transactional public void updateRoute(Long routeId,boolean enabled,String remark,UserAccount user,Authentication auth){requireRoute(routeId,user,auth);mapper.updateRoute(routeId,enabled,blank(remark),user.getId());}
    @Transactional public void deleteRoute(Long routeId,UserAccount user,Authentication auth){requireRoute(routeId,user,auth);mapper.softDeleteRoute(routeId,user.getId());}
    @Transactional(readOnly=true) public java.util.List<RouteTargetSummary> targets(Long routeId,UserAccount user,Authentication auth){ModelRouteSummary route=requireRoute(routeId,user,auth);return mapper.findRouteTargets(route.getId());}
    @Transactional public void createTarget(Long routeId,Long channelId,Long channelModelId,Integer priority,Integer weight,String remark,UserAccount user,Authentication auth){requireRoute(routeId,user,auth);int p=priority==null?100:priority,w=weight==null?100:weight;if(p<0||p>100000||w<1||w>100000)throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"路由优先级或权重不合法");if(!mapper.validRouteTarget(routeId,channelId,channelModelId))throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"当前通道协议与路由协议不一致，或上游模型不可用");mapper.insertRouteTarget(routeId,channelId,channelModelId,p,w,blank(remark),user.getId());}
    @Transactional public void updateTarget(Long routeId,Long targetId,Integer priority,Integer weight,boolean enabled,String remark,UserAccount user,Authentication auth){requireRoute(routeId,user,auth);if(mapper.findRouteTargets(routeId).stream().noneMatch(t->targetId.equals(t.getId())))throw new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"路由目标不存在");int p=priority==null?100:priority,w=weight==null?100:weight;if(p<0||p>100000||w<1||w>100000)throw new ProviderException(BusinessErrorCode.VALIDATION_ERROR,"路由优先级或权重不合法");mapper.updateRouteTarget(targetId,p,w,enabled,blank(remark),user.getId());}
    @Transactional public void deleteTarget(Long routeId,Long targetId,UserAccount user,Authentication auth){requireRoute(routeId,user,auth);if(mapper.findRouteTargets(routeId).stream().noneMatch(t->targetId.equals(t.getId())))throw new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"路由目标不存在");mapper.softDeleteRouteTarget(targetId,user.getId());}
    private ModelRouteSummary requireRoute(Long routeId,UserAccount user,Authentication auth){ModelRouteSummary route=mapper.findRoute(routeId).orElseThrow(()->new ProviderException(BusinessErrorCode.RESOURCE_NOT_FOUND,"模型路由不存在"));requireTenantModel(route.getTenantModelId(),user,auth);return route;}
    @Transactional(readOnly=true) public java.util.List<PublicModelCatalogItem> publicModels(UserAccount user){if(user.getTenantId()==null)throw new ProviderException(BusinessErrorCode.ACCESS_DENIED,"当前账号没有此操作权限");return mapper.findPublicModels(user.getTenantId());}
}
