package io.fluxora.platform.model;

import java.time.Instant;

/** 平台模型目录安全投影；不含上游通道、凭证、成本或内部映射。 */
public class PlatformModelSummary {
    private Long id; private String code; private String displayName; private String description; private String modelType; private String tags;
    private boolean supportsStreaming; private boolean supportsTools; private boolean supportsVision; private boolean supportsCache; private Long contextLength; private Long maxOutputLength; private String status; private Instant createdAt; private Instant updatedAt;
    public Long getId(){return id;} public void setId(Long v){id=v;} public String getCode(){return code;} public void setCode(String v){code=v;} public String getDisplayName(){return displayName;} public void setDisplayName(String v){displayName=v;} public String getDescription(){return description;} public void setDescription(String v){description=v;} public String getModelType(){return modelType;} public void setModelType(String v){modelType=v;} public String getTags(){return tags;} public void setTags(String v){tags=v;} public boolean isSupportsStreaming(){return supportsStreaming;} public void setSupportsStreaming(boolean v){supportsStreaming=v;} public boolean isSupportsTools(){return supportsTools;} public void setSupportsTools(boolean v){supportsTools=v;} public boolean isSupportsVision(){return supportsVision;} public void setSupportsVision(boolean v){supportsVision=v;} public boolean isSupportsCache(){return supportsCache;} public void setSupportsCache(boolean v){supportsCache=v;} public Long getContextLength(){return contextLength;} public void setContextLength(Long v){contextLength=v;} public Long getMaxOutputLength(){return maxOutputLength;} public void setMaxOutputLength(Long v){maxOutputLength=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public Instant getCreatedAt(){return createdAt;} public void setCreatedAt(Instant v){createdAt=v;} public Instant getUpdatedAt(){return updatedAt;} public void setUpdatedAt(Instant v){updatedAt=v;}
}
