<script setup lang="ts">
import { computed, h, onMounted, reactive, ref } from 'vue'
import { NButton, NDropdown, useDialog, useMessage } from 'naive-ui'
import { createChannelModel, deleteChannelModel, listChannelModels, listPlatformModels, mapChannelModel, syncChannelModels, updateChannelModel, type ChannelModelSummary, type PlatformModelSummary, type SyncResult } from '@/services/modelCatalog'
import { useAuthStore } from '@/stores/auth'
const props=defineProps<{channelId:number; canManage:boolean}>(), auth=useAuthStore(),message=useMessage(),dialog=useDialog(),rows=ref<ChannelModelSummary[]>([]),models=ref<PlatformModelSummary[]>([]),syncResult=ref<SyncResult|null>(null),loading=ref(false),editor=ref(false),editing=ref<ChannelModelSummary|null>(null),mapping=ref<ChannelModelSummary|null>(null),mappedId=ref<number|null>(null),form=reactive({upstreamModelId:'',displayName:'',enabled:true})
async function load(){loading.value=true;try{rows.value=(await listChannelModels(props.channelId)).items;if(auth.isPlatformAdmin&&!models.value.length)models.value=(await listPlatformModels({page:1,size:100})).items}catch(e:any){message.error(e.userMessage||'加载候选模型失败')}finally{loading.value=false}}
function openAdd(){editing.value=null;Object.assign(form,{upstreamModelId:'',displayName:'',enabled:true});editor.value=true}function openEdit(r:ChannelModelSummary){editing.value=r;Object.assign(form,{upstreamModelId:r.upstreamModelId,displayName:r.displayName,enabled:r.status==='ENABLED'});editor.value=true}
async function save(){if(!form.upstreamModelId.trim()||!form.displayName.trim()){message.warning('请填写上游模型 ID 和名称');return}try{if(editing.value)await updateChannelModel(props.channelId,editing.value.id,form.displayName.trim(),form.enabled);else await createChannelModel(props.channelId,form.upstreamModelId.trim(),form.displayName.trim());editor.value=false;await load();message.success('候选模型已保存')}catch(e:any){message.error(e.userMessage||'候选模型保存失败')}}
async function sync(){try{const r=await syncChannelModels(props.channelId);syncResult.value=r;await load();message.success(`同步完成：新增 ${r.added}，更新 ${r.updated}，跳过 ${r.skipped}，失败 ${r.failed}`)}catch(e:any){message.error(e.userMessage||'模型同步失败，请检查通道、凭证和接入地址')}}
function remove(r:ChannelModelSummary){dialog.warning({title:'删除候选模型',content:`确定删除「${r.displayName}」吗？已有路由目标会保留模型快照，但不再允许新增引用。`,positiveText:'删除',negativeText:'取消',onPositiveClick:async()=>{try{await deleteChannelModel(props.channelId,r.id);await load();message.success('候选模型已删除')}catch(e:any){message.error(e.userMessage||'删除失败，请稍后重试')}}})}
function openMapping(r:ChannelModelSummary){mapping.value=r;mappedId.value=r.platformModelId;}
async function saveMapping(){if(!mapping.value)return;try{await mapChannelModel(props.channelId,mapping.value.id,mappedId.value);mapping.value=null;await load();message.success(mappedId.value?'候选已映射到平台模型':'候选映射已解除')}catch(e:any){message.error(e.userMessage||'映射保存失败')}}
const cols=computed<any>(()=>[{title:'模型',key:'displayName',minWidth:180,render:(r:ChannelModelSummary)=>h('div',[h('strong',r.displayName),h('small',{style:'display:block;color:var(--text-muted)'},r.upstreamModelId)])},{title:'来源',key:'sourceType',width:90},{title:'映射',key:'mapping',minWidth:140,render:(r:ChannelModelSummary)=>r.platformModelId?models.value.find(x=>x.id===r.platformModelId)?.displayName||`#${r.platformModelId}`:'未映射'},{title:'状态',key:'status',width:80},{title:'操作',key:'action',width:120,render:(r:ChannelModelSummary)=>h(NDropdown,{trigger:'click',options:[...(props.canManage?[{label:'编辑 / 启停',key:'edit'},{label:'删除',key:'delete'}]:[]),...(auth.isPlatformAdmin?[{label:'映射平台模型',key:'map'}]:[])],onSelect:(k:string)=>k==='edit'?openEdit(r):k==='delete'?remove(r):openMapping(r)},()=>h(NButton,{text:true},()=> '管理'))}])
onMounted(()=>void load())
</script>
<template><section><div class="head"><p>每个通道独立维护候选；平台映射显式绑定，不按名称自动合并。</p><n-space><n-button v-if="canManage" size="small" @click="openAdd">手工新增</n-button><n-button v-if="canManage" size="small" @click="sync">自动同步</n-button></n-space></div><n-alert v-if="syncResult" type="info" closable style="margin-bottom:10px" @close="syncResult=null"><strong>同步结果：新增 {{syncResult.added}}，更新 {{syncResult.updated}}，跳过 {{syncResult.skipped}}，失败 {{syncResult.failed}}</strong><div v-for="(i,index) in syncResult.items" :key="index" class="sync-item">{{i.upstreamModelId||'—'}} · {{i.result}} · {{i.reason}}</div></n-alert><n-data-table :columns="cols" :data="rows" :loading="loading" :pagination="false" :scroll-x="650"/><n-modal v-model:show="editor" preset="card" :title="editing?'编辑候选模型':'手工新增候选模型'" style="max-width:460px"><n-form label-placement="top"><n-form-item label="上游模型 ID" required><n-input v-model:value="form.upstreamModelId" :disabled="!!editing" placeholder="例如 gpt-4o"/></n-form-item><n-form-item label="展示名称" required><n-input v-model:value="form.displayName"/></n-form-item><n-form-item v-if="editing" label="启用"><n-switch v-model:value="form.enabled"/></n-form-item></n-form><template #footer><n-button @click="editor=false">取消</n-button><n-button type="primary" @click="save">保存</n-button></template></n-modal><n-modal :show="!!mapping" preset="card" title="映射平台模型" style="max-width:460px" @update:show="v=>{if(!v)mapping=null}"><p class="tip">解除映射不会删除候选；同名候选也不会被系统自动合并。</p><n-select v-model:value="mappedId" clearable filterable :options="models.map(m=>({label:m.displayName+' · '+m.code,value:m.id}))" placeholder="选择平台模型"/><template #footer><n-button @click="mapping=null">取消</n-button><n-button type="primary" @click="saveMapping">保存映射</n-button></template></n-modal></section></template>
<style scoped>.head{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:10px}.head p{margin:0;flex:1;color:var(--text-muted);font-size:12px}.tip,.sync-item{color:var(--text-muted);font-size:12px}.sync-item{margin-top:4px;font-family:var(--font-mono)}</style>
