package io.fluxora.gateway.relay.failure;

/** Gateway 内部失败分类；只进入审计/调度，不直接暴露给客户端。 */
public enum FailureKind {
    NETWORK_PRE_SEND_FAILURE,
    NETWORK_PARTIAL_SEND_FAILURE,
    TLS_FAILURE,
    CONNECT_TIMEOUT,
    FIRST_BYTE_TIMEOUT,
    READ_TIMEOUT,
    AUTH_INVALID,
    AUTH_PERMISSION_DENIED,
    UPSTREAM_BILLING_EXHAUSTED,
    RATE_LIMITED,
    MODEL_MAPPING_INVALID,
    CLIENT_REQUEST_INVALID,
    UPSTREAM_OVERLOADED,
    UPSTREAM_SERVER_ERROR,
    UPSTREAM_RESPONSE_INVALID,
    STREAM_ERROR_BEFORE_EXECUTION,
    STREAM_INTERRUPTED,
    AMBIGUOUS_UPSTREAM_EXECUTION,
    CLIENT_DISCONNECTED,
    UNKNOWN
}
