<script setup lang="ts">
import { computed, h, onMounted, reactive, ref } from 'vue'
import { NButton, NIcon, useMessage } from 'naive-ui'
import { Plus, Search } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/auth'
import MetricStrip from '@/components/MetricStrip.vue'
import StatusDot from '@/components/StatusDot.vue'
import { createPlatformModel, listPlatformModels, platformPriceHistory, setPlatformModelEnabled, setPlatformPrice, updatePlatformModel, type PlatformModelPayload, type PlatformModelSummary, type PriceView } from '@/services/modelCatalog'

const auth=useAuthStore(), message=useMessage(), rows=ref<PlatformModelSummary[]>([]), total=ref(0), loading=ref(false), editorOpen=ref(false), editing=ref<PlatformModelSummary|null>(null), priceOpen=ref(false), pricing=ref<PlatformModelSummary|null>(null), priceRows=ref<PriceView[]>([]), saving=ref(false), keyword=ref(''), page=ref(1)
const form=reactive<PlatformModelPayload>({code:'',displayName:'',description:'',modelType:'TEXT',tags:'',supportsStreaming:true,supportsTools:false,supportsVision:false,supportsCache:false,enabled:true})
const priceForm=reactive({inputPrice:'',outputPrice:'',cacheWritePrice:'',cacheReadPrice:''})
const metrics=computed(()=>[{label:'模型总数',value:total.value},{label:'当前页启用',value:rows.value.filter(x=>x.status==='ENABLED').length},{label:'支持缓存',value:rows.value.filter(x=>x.supportsCache).length},{label:'已停用',value:rows.value.filter(x=>x.status==='DISABLED').length,tone:'warn' as const}])
async function load(){loading.value=true;try{const data=await listPlatformModels({keyword:keyword.value||undefined,page:page.value,size:20});rows.value=data.items;total.value=data.total}catch(e:any){message.error(e.userMessage||'加载失败，请稍后重试')}finally{loading.value=false}}
function open(){editing.value=null;Object.assign(form,{code:'',displayName:'',description:'',modelType:'TEXT',tags:'',supportsStreaming:true,supportsTools:false,supportsVision:false,supportsCache:false,enabled:true});editorOpen.value=true}
function edit(r:PlatformModelSummary){editing.value=r;Object.assign(form,r);editorOpen.value=true}
async function save(){if(!form.code?.trim()||!form.displayName?.trim()){message.warning('请填写模型编码和展示名称');return}saving.value=true;try{if(editing.value)await updatePlatformModel(editing.value.id,form);else await createPlatformModel({...form,code:form.code.trim(),displayName:form.displayName.trim()});message.success(editing.value?'平台模型已更新':'平台模型已创建');editorOpen.value=false;await load()}catch(e:any){message.error(e.userMessage||'保存失败，请稍后重试')}finally{saving.value=false}}
async function openPrice(r:PlatformModelSummary){pricing.value=r;Object.assign(priceForm,{inputPrice:'',outputPrice:'',cacheWritePrice:'',cacheReadPrice:''});try{priceRows.value=await platformPriceHistory(r.id);priceOpen.value=true}catch(e:any){message.error(e.userMessage||'价格历史加载失败')}}
async function savePrice(){if(!pricing.value)return;try{await setPlatformPrice(pricing.value.id,priceForm);priceRows.value=await platformPriceHistory(pricing.value.id);message.success('平台默认价格已生效')}catch(e:any){message.error(e.userMessage||'请输入有效的人民币价格')}}
async function toggle(r:PlatformModelSummary){try{await setPlatformModelEnabled(r.id,r.status!=='ENABLED');message.success(r.status==='ENABLED'?'已停用':'已启用');await load()}catch(e:any){message.error(e.userMessage||'状态更新失败，请稍后重试')}}
const columns=computed<any>(()=>[{title:'模型',key:'model',minWidth:200,render:(r:PlatformModelSummary)=>h('div',{class:'model-cell'},[h('strong',r.displayName),h('span',r.code)])},{title:'能力',key:'cap',minWidth:190,render:(r:PlatformModelSummary)=>['流式',r.supportsTools?'工具':'',r.supportsVision?'视觉':'',r.supportsCache?'缓存':''].filter(Boolean).join(' · ')},{title:'上下文',key:'contextLength',width:110,render:(r:PlatformModelSummary)=>r.contextLength?.toLocaleString()||'—'},{title:'状态',key:'status',width:100,render:(r:PlatformModelSummary)=>h(StatusDot,{status:r.status})},{title:'操作',key:'action',width:180,render:(r:PlatformModelSummary)=>h('div',{style:'display:flex;gap:10px'},[h(NButton,{text:true,onClick:()=>edit(r)},()=> '编辑'),h(NButton,{text:true,onClick:()=>openPrice(r)},()=> '价格'),h(NButton,{text:true,onClick:()=>toggle(r)},()=>r.status==='ENABLED'?'停用':'启用')])}])
onMounted(()=>void load())
</script>
<template><section class="model-page"><header class="page-hdr"><div><h1>平台模型库</h1><p>维护统一对外模型编码、能力元数据与发布基础。</p></div><n-button v-if="auth.isPlatformAdmin" type="primary" @click="open"><template #icon><n-icon><Plus/></n-icon></template>新建模型</n-button></header><MetricStrip :items="metrics"/><div class="toolbar"><label class="search"><n-icon><Search :size="16"/></n-icon><input v-model="keyword" placeholder="搜索模型编码或名称" @keyup.enter="page=1;load()"/></label><n-button @click="page=1;load()">查询</n-button></div><div class="table-region"><n-data-table :columns="columns" :data="rows" :loading="loading" :pagination="false" :bordered="false" :scroll-x="760" flex-height/><n-empty v-if="!loading&&!rows.length" description="还没有平台模型，请从上游候选映射或手工新建。"/></div><footer><span>共 {{total}} 个模型</span><n-pagination v-model:page="page" :item-count="total" :page-size="20" @update:page="load"/></footer><n-modal v-model:show="editorOpen" preset="card" :title="editing?'编辑平台模型':'新建平台模型'" style="max-width:560px"><n-form label-placement="top"><n-form-item label="模型编码" required><n-input v-model:value="form.code" :disabled="!!editing" placeholder="例如 glm-5.2"/><template #feedback>编码是稳定的对外标识，创建后不可修改。</template></n-form-item><n-form-item label="展示名称" required><n-input v-model:value="form.displayName" placeholder="例如 GLM-5.2"/></n-form-item><n-form-item label="说明"><n-input v-model:value="form.description" type="textarea"/></n-form-item><n-form-item label="能力"><n-space><n-checkbox v-model:checked="form.supportsStreaming">支持流式</n-checkbox><n-checkbox v-model:checked="form.supportsTools">工具调用</n-checkbox><n-checkbox v-model:checked="form.supportsVision">视觉输入</n-checkbox><n-checkbox v-model:checked="form.supportsCache">支持缓存</n-checkbox></n-space></n-form-item></n-form><template #footer><n-button @click="editorOpen=false">取消</n-button><n-button type="primary" :loading="saving" @click="save">保存</n-button></template></n-modal><n-drawer v-model:show="priceOpen" placement="right" :width="520"><n-drawer-content :title="`${pricing?.displayName||''} · 平台默认价格`"><p class="hint">金额使用 CNY 十进制字符串，最多 8 位小数。</p><n-form label-placement="top"><n-form-item label="输入价格"><n-input v-model:value="priceForm.inputPrice"/></n-form-item><n-form-item label="输出价格"><n-input v-model:value="priceForm.outputPrice"/></n-form-item><n-space v-if="pricing?.supportsCache"><n-form-item label="缓存写入"><n-input v-model:value="priceForm.cacheWritePrice"/></n-form-item><n-form-item label="缓存读取"><n-input v-model:value="priceForm.cacheReadPrice"/></n-form-item></n-space><n-button type="primary" @click="savePrice">发布新价格</n-button></n-form><n-divider>历史版本</n-divider><div v-for="p in priceRows" :key="p.effectiveAt" class="price-row">{{p.effectiveAt}} · {{p.inputPrice}} / {{p.outputPrice}} · {{p.expiresAt?'已失效':'当前'}}</div></n-drawer-content></n-drawer></section></template>
<style scoped>.model-page{height:100%;display:grid;grid-template-rows:auto auto auto 1fr auto;gap:20px;min-height:0}.page-hdr{display:flex;justify-content:space-between;align-items:flex-end;gap:16px}.page-hdr h1{margin:0;font-size:22px}.page-hdr p,.hint{margin:4px 0 0;color:var(--text-muted);font-size:13px}.toolbar{display:flex;gap:10px}.search{width:min(390px,100%);display:flex;align-items:center;gap:8px;border:1px solid var(--border);border-radius:8px;padding:0 10px}.search input{width:100%;height:34px;border:0;outline:0;background:transparent;color:var(--text)}.table-region{min-height:0;overflow:hidden}.model-cell{display:flex;flex-direction:column;gap:3px}.model-cell span{font-family:var(--font-mono);font-size:12px;color:var(--text-muted)}.price-row{padding:8px 0;border-bottom:1px solid var(--border);font-size:12px;color:var(--text-muted)}footer{display:flex;justify-content:space-between;align-items:center;color:var(--text-muted);font-size:13px}@media(max-width:720px){.page-hdr{align-items:flex-start;flex-direction:column}}</style>
