<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { listPublicModels } from '@/services/modelCatalog'
const rows=ref<any[]>([]), loading=ref(false), keyword=ref('')
const filtered=computed(()=>rows.value.filter(x=>!keyword.value||`${x.code} ${x.displayName}`.toLowerCase().includes(keyword.value.toLowerCase())))
async function load(){loading.value=true;try{rows.value=await listPublicModels()}finally{loading.value=false}}
onMounted(()=>void load())
</script>
<template><main class="catalog"><header><h1>模型目录</h1><p>当前租户已发布、可调用的模型与标准价格。</p><input v-model="keyword" placeholder="搜索模型名称或编码" aria-label="搜索模型"/></header><n-spin :show="loading"><div v-if="filtered.length" class="models"><article v-for="m in filtered" :key="m.code"><div><h2>{{m.displayName}}</h2><code>{{m.code}}</code></div><p>{{m.description||'—'}}</p><dl><div><dt>输入</dt><dd>{{m.inputPrice}} {{m.currencyCode}}</dd></div><div><dt>输出</dt><dd>{{m.outputPrice}} {{m.currencyCode}}</dd></div></dl><footer>{{[m.supportsStreaming&&'流式',m.supportsTools&&'工具',m.supportsVision&&'视觉',m.supportsCache&&'缓存'].filter(Boolean).join(' · ')}}</footer></article></div><n-empty v-else description="暂时没有可用模型"/></n-spin></main></template>
<style scoped>.catalog{max-width:1080px;margin:0 auto;padding:48px 24px}.catalog header{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:32px}.catalog h1{font-size:30px;margin:0}.catalog p{color:var(--text-muted)}input{height:38px;width:280px;padding:0 12px;border:1px solid var(--border);border-radius:8px;background:var(--surface);color:var(--text)}.models{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:14px}article{border:1px solid var(--border);border-radius:10px;padding:18px;background:var(--surface)}article>div{display:flex;justify-content:space-between;gap:8px}h2{font-size:16px;margin:0}code{font-size:12px;color:var(--text-muted)}dl{display:flex;gap:30px;margin:18px 0}dt,footer{font-size:12px;color:var(--text-muted)}dd{margin:3px 0 0;font-variant-numeric:tabular-nums}@media(max-width:720px){.catalog{padding:28px 16px}.catalog header{align-items:flex-start;flex-direction:column}input{width:100%}}</style>
