<script setup lang="ts">
import { computed, h, onMounted, ref, watch } from 'vue'
import type { DataTableColumns } from 'naive-ui'
import MetricStrip from '@/components/MetricStrip.vue'
import { listRequestLogs, requestLogDetail, requestLogStats, requestLogTrends, type RequestLogDetail, type RequestLogSummary, type RequestLogStats, type TrendResponse } from '@/services/requestLogs'
import { useAuthStore } from '@/stores/auth'
const auth=useAuthStore();const message=useMessage();const rows=ref<RequestLogSummary[]>([]);const total=ref(0);const page=ref(1);const loading=ref(false);const stats=ref<RequestLogStats|null>(null);const trends=ref<TrendResponse|null>(null);const range=ref('TODAY');const protocol=ref('');const status=ref('');const model=ref('');const tenantId=ref<number|undefined>(undefined);const detail=ref<RequestLogDetail|null>(null);const showDetail=ref(false);const drawerWidth=ref(520)
const query=computed(()=>({tenantId:tenantId.value,tenantModelCode:model.value||undefined,protocol:protocol.value||undefined,requestStatus:status.value||undefined,page:page.value,size:20}))
async function load(){loading.value=true;try{const [p,s,t]=await Promise.all([listRequestLogs(query.value),requestLogStats(query.value),requestLogTrends({...query.value,range:range.value})]);rows.value=p.items;total.value=p.total;stats.value=s;trends.value=t}catch{message.error('加载请求日志失败，请稍后重试')}finally{loading.value=false}}
watch([range,protocol,status,model,tenantId,page],load);onMounted(()=>{drawerWidth.value=Math.min(520,document.documentElement.clientWidth-32);load()})
function unknown(v:number|null){return v===null?'暂不可得':String(v)} function amount(v:string|null){return v??'待确认'} function time(v:string){return v?.slice(0,16).replace('T',' ')||'—'} function state(v:string){return ({SUCCESS:'成功',FAILED:'失败',CANCELLED:'取消',STARTED:'进行中'} as Record<string,string>)[v]||v} function billing(v:string|null){return ({RESERVED:'已冻结',SETTLED:'已结算',RELEASED:'已释放',RECONCILIATION_PENDING:'待对账',RESERVE_REJECTED:'冻结拒绝'} as Record<string,string>)[v||'']||'—'}
async function open(row:RequestLogSummary){try{detail.value=await requestLogDetail(row.requestId,tenantId.value);showDetail.value=true}catch{message.error('加载请求详情失败，请稍后重试')}}
const metricItems=computed(()=>[{label:'请求总数',value:stats.value?.total??null},{label:'成功请求',value:stats.value?.success??null},{label:'失败请求',value:stats.value?.failed??null,tone:'danger' as const},{label:'输入 / 输出 Token',value:stats.value?.inputTokens??null},{label:'缓存读取 Token',value:stats.value?.cacheReadTokens??null},{label:'理论金额',value:stats.value?.theoreticalAmount??'暂不可得'}])
const columns=computed<DataTableColumns<RequestLogSummary>>(()=>[{title:'请求时间',key:'startedAt',width:150,render:r=>time(r.startedAt)},{title:'请求 ID',key:'requestId',minWidth:180,render:r=>h('button',{class:'request-id',onClick:()=>open(r)},r.requestId)},{title:'模型',key:'tenantModelCode',width:120},{title:'协议',key:'inboundProtocol',width:85},{title:'状态',key:'requestStatus',width:82,render:r=>h('span',{class:`status status-${r.requestStatus.toLowerCase()}`},state(r.requestStatus))},{title:'耗时',key:'durationMs',width:80,render:r=>r.durationMs===null?'—':`${r.durationMs}ms`},{title:'Token 用量',key:'tokens',width:150,render:r=>h('div',{class:'token-cell'},[h('span',{},`${unknown(r.inputTokens)} / ${unknown(r.outputTokens)}`),h('span',{class:'token-cache'},r.cacheReadTokens!=null||r.cacheWriteTokens!=null?`缓存 ${unknown(r.cacheWriteTokens)} / ${unknown(r.cacheReadTokens)}`:'')])},{title:'用量',key:'usageStatus',width:90,render:r=>r.usageStatus==='UNKNOWN'?'暂不可得':r.usageStatus==='PARTIAL'?'部分可得':'完整'},{title:'理论金额',key:'theoreticalAmount',width:110,render:r=>amount(r.theoreticalAmount)},{title:'结算',key:'reservationStatus',width:110,render:r=>h('span',{class:`billing billing-${(r.reservationStatus||'none').toLowerCase().replace(/_/g,'-')}`},billing(r.reservationStatus))},{title:'冻结 / 实扣',key:'billingAmount',width:140,render:r=>h('div',{class:'token-cell'},[h('span',{},amount(r.reservationAmount)),h('span',{class:'token-cache'},`实扣 ${amount(r.actualAmount)}`)])}])
</script>
<template><section class="logs-page"><header class="page-hdr"><div><h1>请求日志与用量</h1><p>理论金额，不代表已扣费。未知或部分未知用量不会按零汇总。</p></div></header><MetricStrip :items="metricItems" :loading="loading"/><div class="toolbar"><div class="chips"><button v-for="x in [{v:'TODAY',l:'今天'},{v:'SEVEN_DAYS',l:'近 7 天'},{v:'THIRTY_DAYS',l:'近 30 天'}]" :key="x.v" :class="{active:range===x.v}" @click="range=x.v">{{x.l}}</button></div><n-select v-model:value="protocol" clearable placeholder="协议" :options="[{label:'OpenAI',value:'OPENAI'},{label:'Anthropic',value:'ANTHROPIC'}]" style="width:130px"/><n-select v-model:value="status" clearable placeholder="状态" :options="[{label:'成功',value:'SUCCESS'},{label:'失败',value:'FAILED'},{label:'取消',value:'CANCELLED'}]" style="width:130px"/><n-input v-model:value="model" clearable placeholder="模型编码" style="width:160px"/><n-input-number v-if="auth.isPlatformAdmin" v-model:value="tenantId" :show-button="false" placeholder="目标租户 ID" style="width:160px"/></div><section class="trend"><div><h2>请求趋势</h2><p>{{ trends?.timeZone||'—' }} · {{ trends?.granularity==='hour'?'按小时':'按自然日' }}</p><div class="bucket-list"><span v-for="b in trends?.buckets||[]" :key="b.bucketStart">{{b.bucketStart.slice(5,16)}}：{{b.requestCount}} 请求</span><span v-if="!trends?.buckets?.length">暂无数据</span></div></div><div><h2>输入 / 输出 Token</h2><p>仅展示已知值；部分数据已明确标注。</p><div class="bucket-list"><span v-for="b in trends?.buckets||[]" :key="b.bucketStart">{{b.bucketStart.slice(5,16)}}：{{unknown(b.inputTokens)}} / {{unknown(b.outputTokens)}}</span><span v-if="!trends?.buckets?.length">暂无数据</span></div></div><div><h2>缓存写入 / 读取 Token</h2><p>缓存命中时输入 Token 从缓存读取侧剥离。</p><div class="bucket-list"><span v-for="b in trends?.buckets||[]" :key="b.bucketStart">{{b.bucketStart.slice(5,16)}}：{{unknown(b.cacheWriteTokens)}} / {{unknown(b.cacheReadTokens)}}</span><span v-if="!trends?.buckets?.length">暂无数据</span></div></div><div><h2>理论金额趋势</h2><p>仅汇总 CALCULATED 请求。</p><div class="bucket-list"><span v-for="b in trends?.buckets||[]" :key="b.bucketStart">{{b.bucketStart.slice(5,16)}}：{{amount(b.calculatedTheoreticalAmount)}}</span><span v-if="!trends?.buckets?.length">暂无数据</span></div></div></section><div class="table"><n-data-table :columns="columns" :data="rows" :loading="loading" :pagination="false" :bordered="false" flex-height/><n-empty v-if="!loading&&!rows.length" description="当前筛选条件下没有请求记录"/></div><footer><span>共 {{total}} 条请求</span><n-pagination v-if="total>20" v-model:page="page" :page-count="Math.ceil(total/20)"/></footer><n-drawer v-model:show="showDetail" :width="drawerWidth"><n-drawer-content title="安全请求详情"><dl v-if="detail" class="detail"><template v-for="[k,v] in Object.entries(detail)" :key="k"><dt>{{k}}</dt><dd>{{v??'—'}}</dd></template></dl></n-drawer-content></n-drawer></section></template>
<style scoped>.logs-page{height:100%;display:grid;grid-template-rows:auto auto auto auto 1fr auto;gap:20px;min-height:0}.page-hdr h1{margin:0;font-size:22px}.page-hdr p,h2+p{margin:5px 0 0;color:var(--text-muted);font-size:13px}.toolbar{display:flex;gap:10px;flex-wrap:wrap}.chips{display:flex;border:1px solid var(--border);border-radius:8px;padding:3px;background:var(--surface-elevated)}.chips button{border:0;background:transparent;padding:5px 10px;color:var(--text-muted);border-radius:5px}.chips .active{background:var(--surface);color:var(--text)}.trend{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.trend>div,.table{border:1px solid var(--border);border-radius:10px;background:var(--surface);padding:16px;min-width:0}.trend h2{margin:0;font-size:14px}.bucket-list{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px;font:12px var(--font-mono);color:var(--text-muted)}.bucket-list span{white-space:nowrap}.table{min-height:0;padding:0;overflow:hidden;display:flex;flex-direction:column}.table :deep(.n-data-table){flex:1;min-height:0}.request-id{border:0;background:transparent;color:var(--accent);font:inherit;cursor:pointer}.token-cell{display:flex;flex-direction:column;gap:2px}.token-cache{font-size:11px;color:var(--text-muted)}.status{display:inline-flex;align-items:center;gap:5px}.status::before{content:'';width:7px;height:7px;border-radius:50%;background:currentColor}.status-success{color:#20a779}.status-failed{color:var(--danger)}.status-cancelled{color:#d98b20}.status-started{color:var(--text-muted)}footer{display:flex;justify-content:space-between;align-items:center;color:var(--text-muted);font-size:13px}.detail{display:grid;grid-template-columns:150px 1fr;gap:12px;margin:0;font-size:13px}.detail dt{color:var(--text-muted)}.detail dd{margin:0;overflow-wrap:anywhere}@media(max-width:1100px){.trend{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:720px){.trend{grid-template-columns:1fr}.detail{grid-template-columns:92px 1fr}}</style>
<style scoped>
.billing{display:inline-flex;padding:2px 7px;border-radius:4px;font-size:12px;background:var(--surface-elevated);color:var(--text-muted)}
.billing-settled{color:#20a779;background:color-mix(in srgb,#20a779 12%,transparent)}
.billing-reconciliation-pending{color:#d98b20;background:color-mix(in srgb,#d98b20 12%,transparent)}
.billing-reserve-rejected{color:var(--danger);background:color-mix(in srgb,var(--danger) 12%,transparent)}
</style>
