<script setup lang="ts">
import { h, onMounted, reactive, ref } from 'vue'
import { NButton, useDialog, useMessage } from 'naive-ui'
import { createModelRoute, createRouteTarget, currentTenantPrice, deleteModelRoute, deleteRouteTarget, enableTenantModel, inheritTenantPrice, listChannelModels, listModelRoutes, listPlatformModels, listRouteTargets, listTenantModels, publishTenantModel, setTenantCustomPrice, tenantPriceHistory, updateModelRoute, updateRouteTarget, type ChannelModelSummary, type ModelRouteSummary, type PlatformModelSummary, type PriceView, type RouteTargetSummary, type TenantModelSummary } from '@/services/modelCatalog'
import { listProviderChannels, type ProviderChannelSummary } from '@/services/upstream'
import { listTenants, type Tenant } from '@/services/tenant'
import { useAuthStore } from '@/stores/auth'

const auth=useAuthStore(), message=useMessage(), dialog=useDialog(), available=ref<PlatformModelSummary[]>([]), published=ref<TenantModelSummary[]>([]), channels=ref<ProviderChannelSummary[]>([]), tenants=ref<Tenant[]>([]), tenantId=ref<number|null>(null), loading=ref(false)
const detail=ref<TenantModelSummary|null>(null), routes=ref<ModelRouteSummary[]>([]), targets=ref<RouteTargetSummary[]>([]), candidateModels=ref<ChannelModelSummary[]>([])
const price=ref<PriceView|null>(null), priceHistory=ref<PriceView[]>([]), detailOpen=ref(false), routeOpen=ref(false), targetOpen=ref(false), priceOpen=ref(false)
const routeForm=reactive({ inboundProtocol:'OPENAI' as 'OPENAI'|'ANTHROPIC', remark:'' }), targetForm=reactive({ routeId:null as number|null, providerChannelId:null as number|null, providerChannelModelId:null as number|null, priority:100, weight:100, remark:'' }), priceForm=reactive({ inputPrice:'',outputPrice:'',cacheWritePrice:'',cacheReadPrice:'' })
async function load(){ if(auth.isPlatformAdmin&&!tenantId.value)return;loading.value=true;try{const [a,p,c]=await Promise.all([listPlatformModels({enabled:true,page:1,size:100}),listTenantModels(tenantId.value||undefined),listProviderChannels({tenantId:tenantId.value||undefined,page:1,size:100})]);available.value=a.items;published.value=p.items;channels.value=c.items}catch(e:any){message.error(e.userMessage||'加载失败，请稍后重试')}finally{loading.value=false} }
async function publish(m:PlatformModelSummary){try{await publishTenantModel(m.id,undefined,undefined,tenantId.value||undefined);message.success('模型已发布为草稿，请继续配置价格和路由');await load()}catch(e:any){message.error(e.userMessage||'发布失败，请稍后重试')}}
async function openDetail(m:TenantModelSummary){ detail.value=m; detailOpen.value=true; try{const [r,p,h]=await Promise.all([listModelRoutes(m.id),currentTenantPrice(m.id).catch(()=>null),tenantPriceHistory(m.id)]);routes.value=r;price.value=p;priceHistory.value=h}catch(e:any){message.error(e.userMessage||'加载模型配置失败，请稍后重试')} }
async function openTargets(route:ModelRouteSummary){ targetForm.routeId=route.id; targetForm.providerChannelId=null; targetForm.providerChannelModelId=null; targets.value=await listRouteTargets(route.id); targetOpen.value=true }
async function chooseChannel(){ candidateModels.value=[]; if(!targetForm.providerChannelId)return; try{candidateModels.value=(await listChannelModels(targetForm.providerChannelId)).items}catch(e:any){message.error(e.userMessage||'加载上游候选失败，请稍后重试')} }
async function saveRoute(){ if(!detail.value)return; try{await createModelRoute(detail.value.id,routeForm.inboundProtocol,routeForm.remark||undefined);routeOpen.value=false;await openDetail(detail.value);message.success('路由已创建')}catch(e:any){message.error(e.userMessage||'保存失败，请稍后重试')} }
async function saveTarget(){if(!targetForm.routeId||!targetForm.providerChannelId||!targetForm.providerChannelModelId){message.warning('请选择通道和上游模型');return}try{await createRouteTarget(targetForm.routeId,{providerChannelId:targetForm.providerChannelId,providerChannelModelId:targetForm.providerChannelModelId,priority:targetForm.priority,weight:targetForm.weight,remark:targetForm.remark||undefined});targets.value=await listRouteTargets(targetForm.routeId);message.success('路由目标已添加')}catch(e:any){message.error(e.userMessage||'路由目标保存失败，请检查协议与模型状态')}}
async function toggleRoute(r:ModelRouteSummary){try{await updateModelRoute(r.id,r.status!=='ENABLED',r.remark||undefined);if(detail.value)await openDetail(detail.value);message.success(r.status==='ENABLED'?'路由已停用':'路由已启用')}catch(e:any){message.error(e.userMessage||'路由状态更新失败')}}
function removeRoute(r:ModelRouteSummary){dialog.warning({title:'删除路由',content:`确定删除 ${r.inboundProtocol} 路由吗？`,positiveText:'删除',negativeText:'取消',onPositiveClick:async()=>{try{await deleteModelRoute(r.id);if(detail.value)await openDetail(detail.value);message.success('路由已删除')}catch(e:any){message.error(e.userMessage||'路由删除失败')}}})}
async function toggleTarget(t:RouteTargetSummary){if(!targetForm.routeId)return;try{await updateRouteTarget(targetForm.routeId,t.id,{priority:t.priority,weight:t.weight,enabled:t.status!=='ENABLED',remark:t.remark||undefined});targets.value=await listRouteTargets(targetForm.routeId)}catch(e:any){message.error(e.userMessage||'目标状态更新失败')}}
function removeTarget(t:RouteTargetSummary){if(!targetForm.routeId)return;const routeId=targetForm.routeId;dialog.warning({title:'删除路由目标',content:`确定删除 ${t.channelName} · ${t.upstreamModelIdSnapshot} 吗？`,positiveText:'删除',negativeText:'取消',onPositiveClick:async()=>{try{await deleteRouteTarget(routeId,t.id);targets.value=await listRouteTargets(routeId);message.success('路由目标已删除')}catch(e:any){message.error(e.userMessage||'删除失败')}}})}
async function savePrice(){if(!detail.value||!priceForm.inputPrice||!priceForm.outputPrice){message.warning('请填写输入和输出单价');return}try{price.value=await setTenantCustomPrice(detail.value.id,priceForm);priceOpen.value=false;await openDetail(detail.value);message.success('自定义价格已生效')}catch(e:any){message.error(e.userMessage||'请输入有效的人民币价格')}}
async function inherit(){if(!detail.value)return;try{await inheritTenantPrice(detail.value.id);await openDetail(detail.value);message.success('已继承平台默认价格')}catch(e:any){message.error(e.userMessage||'平台默认价格尚未配置')}}
async function enable(){if(!detail.value)return;try{await enableTenantModel(detail.value.id);message.success('模型已发布');await load();await openDetail(detail.value)}catch(e:any){message.error(e.userMessage||'请先配置有效价格和至少一个可用路由目标')}}
const cols=[{title:'模型',key:'displayName'},{title:'编码',key:'platformCode'},{title:'状态',key:'publishStatus'},{title:'价格模式',key:'priceMode'},{title:'操作',key:'id',render:(r:TenantModelSummary)=>h(NButton,{text:true,onClick:()=>openDetail(r)},()=> '配置')}]
onMounted(async()=>{if(auth.isPlatformAdmin){try{tenants.value=(await listTenants({page:1,size:100})).items;tenantId.value=tenants.value[0]?.id||null}catch{message.error('租户列表加载失败，请稍后重试')}}await load()})
</script>
<template><section class="page"><header><div><h1>租户模型</h1><p>发布草稿后，配置价格、协议路由与上游候选；所有条件满足才可对外启用。</p></div><n-select v-if="auth.isPlatformAdmin" v-model:value="tenantId" :options="tenants.map(t=>({label:t.name+' · '+t.tenantCode,value:t.id}))" placeholder="选择租户" style="width:240px" @update:value="load"/></header><n-spin :show="loading"><h2>已发布模型</h2><n-data-table :data="published" :pagination="false" :columns="cols" :scroll-x="720"/><h2>可发布平台模型</h2><n-data-table :data="available" :pagination="false" :columns="[{title:'模型',key:'displayName'},{title:'编码',key:'code'},{title:'操作',key:'id',render:(r:any)=>h(NButton,{onClick:()=>publish(r)},()=> '发布为草稿')}]" :scroll-x="520"/></n-spin>
<n-drawer v-model:show="detailOpen" placement="right" :width="720"><n-drawer-content v-if="detail" :title="detail.displayName"><div class="summary"><span>状态：{{detail.publishStatus}}</span><span>价格：{{price ? `${price.inputPrice} / ${price.outputPrice} CNY` : '尚未配置'}}</span><n-button size="small" @click="priceOpen=true">设置价格</n-button><n-button size="small" @click="inherit">继承平台价</n-button><n-button type="primary" size="small" @click="enable">启用发布</n-button></div><n-collapse v-if="priceHistory.length" style="margin-top:12px"><n-collapse-item title="自定义价格历史"><div v-for="p in priceHistory" :key="p.effectiveAt" class="history">{{p.effectiveAt}} · 输入 {{p.inputPrice}} / 输出 {{p.outputPrice}} · {{p.expiresAt?'已失效':'当前'}}</div></n-collapse-item></n-collapse><n-divider>路由</n-divider><n-button size="small" @click="routeOpen=true">新增协议路由</n-button><div v-for="r in routes" :key="r.id" class="route"><strong>{{r.inboundProtocol}}</strong><span>{{r.status}}</span><n-button text @click="openTargets(r)">管理目标</n-button><n-button text @click="toggleRoute(r)">{{r.status==='ENABLED'?'停用':'启用'}}</n-button><n-button text type="error" @click="removeRoute(r)">删除</n-button></div></n-drawer-content></n-drawer>
<n-modal v-model:show="routeOpen" preset="card" title="新增协议路由" style="max-width:440px"><n-form label-placement="top"><n-form-item label="入站协议"><n-select v-model:value="routeForm.inboundProtocol" :options="[{label:'OPENAI',value:'OPENAI'},{label:'ANTHROPIC',value:'ANTHROPIC'}]"/></n-form-item><n-form-item label="备注"><n-input v-model:value="routeForm.remark"/></n-form-item></n-form><template #footer><n-button @click="routeOpen=false">取消</n-button><n-button type="primary" @click="saveRoute">保存</n-button></template></n-modal>
<n-modal v-model:show="priceOpen" preset="card" title="设置自定义价格" style="max-width:460px"><p class="hint">价格以 CNY 字符串填写，最多 8 位小数，不支持科学计数法。</p><n-form label-placement="top"><n-form-item label="输入单价" required><n-input v-model:value="priceForm.inputPrice" placeholder="0.00000001"/></n-form-item><n-form-item label="输出单价" required><n-input v-model:value="priceForm.outputPrice"/></n-form-item><n-form-item v-if="detail?.supportsCache" label="缓存写入 / 读取"><n-space><n-input v-model:value="priceForm.cacheWritePrice"/><n-input v-model:value="priceForm.cacheReadPrice"/></n-space></n-form-item></n-form><template #footer><n-button @click="priceOpen=false">取消</n-button><n-button type="primary" @click="savePrice">保存</n-button></template></n-modal>
<n-drawer v-model:show="targetOpen" placement="right" :width="620"><n-drawer-content title="路由目标"><n-data-table :data="targets" :pagination="false" :columns="[{title:'通道',key:'channelName'},{title:'上游模型',key:'upstreamModelIdSnapshot'},{title:'优先级',key:'priority'},{title:'权重',key:'weight'},{title:'操作',key:'action',render:(t:any)=>h('div',{style:'display:flex;gap:8px'},[h(NButton,{text:true,onClick:()=>toggleTarget(t)},()=>t.status==='ENABLED'?'停用':'启用'),h(NButton,{text:true,type:'error',onClick:()=>removeTarget(t)},()=> '删除')])}]"/><n-divider>添加目标</n-divider><n-form label-placement="top"><n-form-item label="上游通道"><n-select v-model:value="targetForm.providerChannelId" :options="channels.map(c=>({label:`${c.name} · ${c.protocol}`,value:c.id}))" @update:value="chooseChannel"/></n-form-item><n-form-item label="上游模型"><n-select v-model:value="targetForm.providerChannelModelId" :options="candidateModels.map(c=>({label:c.displayName+' · '+c.upstreamModelId,value:c.id}))"/></n-form-item><n-space><n-form-item label="优先级"><n-input-number v-model:value="targetForm.priority" :min="0"/></n-form-item><n-form-item label="权重"><n-input-number v-model:value="targetForm.weight" :min="1"/></n-form-item></n-space></n-form><n-button type="primary" @click="saveTarget">添加路由目标</n-button></n-drawer-content></n-drawer></section></template>
<style scoped>.page{height:100%;display:grid;grid-template-rows:auto 1fr;gap:20px;min-height:0}.page h1{margin:0;font-size:22px}.page p,.hint{color:var(--text-muted);font-size:13px}.page h2{font-size:15px;margin:20px 0 8px}.summary{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.route{display:flex;gap:12px;align-items:center;padding:12px 0;border-bottom:1px solid var(--border)}.history{padding:6px 0;color:var(--text-muted);font-size:12px;font-variant-numeric:tabular-nums}@media(max-width:720px){.summary{align-items:flex-start;flex-direction:column}.route{align-items:flex-start;flex-wrap:wrap}}</style>
